### ISSUE TITLE
defautl admin cannot manage users and groups

### ISSUE THREAD

**Issue by visvic** [tuxgasy/docker-dolibarr#119]
Hi,

I just deployed the container but the default admin does not have rights to modify users/groups. Neither administer the server.

thanks in advance

**Comment by visvic** [comment]
Bonjour,

Petit UP et j'ai du nouveau.
Quand je déploie en version 16, aucun problème, j'ai bien accès au module "utilisateurs/groupes". je peux modifier, ajouter etc...
quand j'update de 16.0.4 vers 17.0.0 je n'ai de nouveau plus accès au modules "utilisateurs/groupes"...

D'ou est-ce que cela peut-il provenir ?

**Comment by LaplancheMaxime** [comment]
Bonjour,

Je pense que c'est  propre à la V17. 
J'ai également le souci, mais ce n'est pas bloquant étant donné que le module était déjà activé avant la migration.
J'ai accès à la configuration du module, mais pas à son activation/désactivation. (en laissant le pointeur sur le bouton d'activation, celle-ci affiche "requis").

Cela doit être un comportement normal.
La question devrait-être posée dans ce repo : https://github.com/Dolibarr/dolibarr/issues

**Comment by visvic** [comment]
Bonjour @LaplancheMaxime 

Merci pour la réponse ;)

Alors je suis nouveau sur Dolibarr, donc je suis partis avec une fresh install en V17. Et de ce fait, dès le début je ne peux pas gérer les utilisateurs/groupes. Donc effectivement, depuis une migration, pourquoi pas, mais la c'est tout frais ^^.
Je ne suis pas sur que cela doit être normal que l'utilisateur admin par défaut n'ait pas le droit de gérer les utilsateurs/groupes ^^.

On va voir s'il y a de prochains update/correctif de Dolibarr.

Merci encore et bonne journée =)

**Comment by chicato83** [comment]
I have the same issue here. Sad.

Any solutions for it?
