### ISSUE TITLE
Upgrade Dolibarr 9.0.0 to 10.0.3

### ISSUE THREAD

**Issue by rajaseg** [tuxgasy/docker-dolibarr#13]
Thanks for the image. I just installed it without any issue. Just wanted to check, how can i upgrade the version from 9.0.0 to 10.0.3?

Thanks in advance.

**Comment by ma0dubois** [comment]
Hi rajaseg,

Where did you find the image  ?
The image is not available on [tuxgasy/dolibarr](https://hub.docker.com/r/tuxgasy/dolibarr/tags?page=1)

**Comment by rajaseg** [comment]
I used https://hub.docker.com/r/tuxgasy/dolibarr

I deployed using docker compose, 
web:
    image: tuxgasy/dolibarr

**Comment by ma0dubois** [comment]
Are you sure about the version ?
The tag "**latest**" is a 9.0.4, see this [Dockerfile](https://hub.docker.com/layers/tuxgasy/dolibarr/latest/images/sha256-0eec4a4cacc3c08f46ae066753dc6f792e0e55673928ac22c41c123a89f25355) à line 33.

Can you verify your installation ? i'm confused

**Comment by rajaseg** [comment]
I have re-deployed it again just now. Please find images below for reference.

![image](https://user-images.githubusercontent.com/633479/71672779-f5310500-2d9c-11ea-8d7d-a672e97981f2.png)

![image](https://user-images.githubusercontent.com/633479/71672802-0548e480-2d9d-11ea-8917-18aab3d34fb7.png)

**Comment by rajaseg** [comment]
Yes, the current version is 9.0.4 and latest version is 10.0.5. is there a way to upgrade from 9.0.4 to 10.0.5?

![image](https://user-images.githubusercontent.com/633479/71672957-5b1d8c80-2d9d-11ea-9d61-94599c8d801c.png)

**Comment by ma0dubois** [comment]
You can reproduce the steps that you see in the Upgrade instructions directly inside your container:
`docker exec-it CONTAINER_NAME /bin/bash`.

Don't forget to persist your volume, otherwise you will loose your upgrade

**Comment by ma0dubois** [comment]
I complete my instructions for an update of Dolibarr:

```sh
# Your target version
export DOLI_VERSION=10.0.6
rm -rf /tmp/dolibarr /tmp/dolibarr.zip
wget https://github.com/Dolibarr/dolibarr/archive/${DOLI_VERSION}.zip -P /tmp
unzip -q /tmp/${DOLI_VERSION}.zip -d /tmp/dolibarr && ls -la /tmp/dolibarr
cp -r /tmp/dolibarr/dolibarr-${DOLI_VERSION}/htdocs/* /var/www/html/ && ln -s /var/www/html /var/www/htdocs
cp -r /tmp/dolibarr/dolibarr-${DOLI_VERSION}/scripts /var/www/
rm -rf /tmp/dolibarr
chown -R www-data:www-data /var/www

# remove the previous lock
rm /var/www/documents/install.lock
# Lancez Dolibarr sur votre navigateur web et effectuez la mise à jour ...

# Une fois la mise à jour terminée
touch /var/www/documents/install.lock && \
chown www-data:www-data /var/www/documents/install.lock && \
chmod 400 /var/www/documents/install.lock
```

**Comment by rajaseg** [comment]
Where to run the above code?

**Comment by ma0dubois** [comment]
> Where to run the above code?

I've updated my previous reponse :)
