### ISSUE TITLE
DOLI_INSTANCE_UNIQUE_ID not set 

### ISSUE THREAD

**Issue by Cajuteq** [tuxgasy/docker-dolibarr#134]
I have set up a DOLI_INSTANCE_UNIQUE_ID in order to fix the INSTANCE_UNIQUE_ID across restart because the ID is used for licensing by a paid module. Docker-compose :
![image](https://github.com/tuxgasy/docker-dolibarr/assets/26676532/eb971dda-5a04-4eef-ba3c-8ea44d9e00be)

Docker image documentation : 
![image](https://github.com/tuxgasy/docker-dolibarr/assets/26676532/ae8061d5-0001-4cc2-abd1-bf0f280b68a8)

However, this leads to the INSTANCE_UNIQUE_ID being empty according to var_dump() :
![image](https://github.com/tuxgasy/docker-dolibarr/assets/26676532/549ae3a0-0443-4a07-90e2-15f298e2741c)

Also, the documentation state that this ID is set at container creation, but this doesn't seem to happen. According to this var_dump($conf) on a fresh container.
![image](https://github.com/tuxgasy/docker-dolibarr/assets/26676532/6deed9d0-dfe2-43c2-88b6-8186518bbe42)

For now, I have a workaround by editing the PHP var directly in the file that uses it, but it's not perfect.

**Comment by tuxgasy** [comment]
Fixed now.
