### ISSUE TITLE
Error when updating from 18.0.4 -> 19.0.0

### ISSUE THREAD

**Issue by SilverResort** [tuxgasy/docker-dolibarr#140]
Hello,
When updating from 18.0.4 to 19.0.0, I see the following error :

SHOW CREATE TABLE llx_mrp_production_extrafields : Table 'dolibarr-prod.llx_mrp_production_extrafields' doesn't exist in engine

It is related to the request 95 which is aiming to add index to the llx_mrp_production_extrafields
Erreur DB_ERROR_1932 (Req 95): ALTER TABLE llx_mrp_production_extrafields ADD INDEX idx_mrp_production_fk_object(fk_object);
Table 'dolibarr.llx_mrp_production_extrafields' doesn't exist in engine

Do you see anything that could cause this ?
Kind Regards

**Comment by Extarys** [comment]
Similar issue here too

https://github.com/Dolibarr/dolibarr/issues/28529

**Comment by Vaadasch** [comment]
@SilverResort this seems to be fixed, can you confirm it and close this issue that is more a Dolibarr-related problem than a doker-image related problem ?
Thanks
