### ISSUE TITLE
installation of a previous version

### ISSUE THREAD

**Issue by zunami** [tuxgasy/docker-dolibarr#142]
hello!

i could not find in the README i can install a previous version of Compose.
I need version 18 to restore the database.

> version: "3.9"
services:
    mariadb:
        image: mariadb:latest
        container_name: Dolibarr-DB
        security_opt:
         - no-new-privileges:true
        environment:
            MYSQL_ROOT_PASSWORD: rootpass
            MYSQL_DATABASE: dolibarr
            MYSQL_USER: doliuser
            MYSQL_PASSWORD: dolipassword
            TZ: Europe/Vienna
        volumes:
            - /volume1/docker/dolibarr/db:/var/lib/mysql:rw
        restart: on-failure:5
    web:
        image: tuxgasy/dolibarr
        container_name: Dolibarr
        environment:
            DOLI_DB_HOST: mariadb
            DOLI_DB_USER: doliuser
            DOLI_DB_PASSWORD: dolipassword
            DOLI_DB_NAME: dolibarr
            PHP_INI_DATE_TIMEZONE: Europe/Vienna
            PHP_INI_MEMORY_LIMIT: 512M
            PHP_INI_UPLOAD_MAX_FILESIZE: 128M
            PHP_INI_POST_MAX_SIZE: 64M
            DOLI_VERSION: 18.0.5
            DOLI_INSTALL_AUTO: 1
            DOLI_PROD: 1
            DOLI_ADMIN_LOGIN: adminuser
            DOLI_ADMIN_PASSWORD: adminpassword
        volumes:
            - /volume1/docker/dolibarr/html:/var/www/html/custom:rw
            - /volume1/docker/dolibarr/documents:/var/www/documents:rw
        ports:
            - 8041:80
        depends_on:
            - mariadb
        restart: on-failure:5

**Comment by Vaadasch** [comment]
Hi @zunami 
Do you need to install a new version of Compose ?
As i understand, you want to use the version 18.0.5 of the dolibarr image, so you need to 
`image: tuxgasy/dolibarr:18.0.5` inside your compose configuration.
By default, without specifying, that is equal to `image: tuxgasy/dolibarr:latest`
