### ISSUE TITLE
Difference between htdocs and html

### ISSUE THREAD

**Issue by vipera7** [tuxgasy/docker-dolibarr#19]
Hello,
I'm trying to create a volume for the dolibarr files. I entered the container and saw two path. 
- /var/www/html
- /var/www/htdocs

Which one should I use for the volume ?

**Comment by mathieupotier** [comment]
I assume you mean for backup files (invoices, orders, pdf, etc..)

For backing up files, you should use `/var/www/documents` as Dolibarr is storing data here, `htdocs` and `html` (which is a symlink for `htdocs`) are for application code source, and should not be backed up.

**Comment by vipera7** [comment]
So I shouldn't make a volum under `/var/www/htdocs` but instead `/var/www/documents` ? But how can I put a volume under the config file ?

**Comment by mathieupotier** [comment]
What do you need to edit in config file ? It has not been planned, as I read the code for those images.
If you need this, maybe slight arrangement could be done in images.
Can you please tell me more about your need ?

**Comment by vipera7** [comment]
Well I want to have a persistent dolibarr instance

**Comment by mathieupotier** [comment]
OK, so I assume that `persistent`means that persistent DB and Data.
Make your DB persistent itself is not the point here, but for this image, persistence is done by mounting a volume in `/var/www/documents` which is the location where Dolibarr store generated files such as orders, invoices, quotations, etc...
Config file don't need backup IMO as it's generated during boot of container with values you pass up through env vars [here](https://github.com/tuxgasy/docker-dolibarr#environment-variables-summary). If you need more configuration options, it has to be dealed by a PR here... ^_^

**Comment by vipera7** [comment]
Oww ok thanks for the reply ! But what if I want to persist the custom module/apps ?

**Comment by mathieupotier** [comment]
`/var/www/html/custom` do you mean this directory ?
Just put a volume for this dir... or maybe better into ` /var/www/htdocs/custom` anyway maybe something could be done in the image to deal with this.
Any suggest @tuxgasy ?
Maybe create a `VOLUME` that links into the relevant directory (in order to avoid future mess)

**Comment by mathieupotier** [comment]
Forget about my previous comment, mounting a persistent volume into `/var/www/html/custom` should do the trick.

**Comment by vipera7** [comment]
@mathieupotier Exactly what I was looking for
