### ISSUE TITLE
How to update Dolibarr with cli

### ISSUE THREAD

**Issue by vipera7** [tuxgasy/docker-dolibarr#21]
Hey,
I'm creating a container with for eg Dolibarr 9.0.4 using a persistent volume for documents and custom folder. I'm also using an external database.
Then I'm stopping the container and deleting it. I recreate it with the same attribute but using the tag `last`.
Now I need to upgrade it. I deleted the file `install.lock` in the documents folder.
Then I need to run the following script (https://wiki.dolibarr.org/index.php/Installation_-_Upgrade): 
- upgrade.php
- upgrade2.php
- step5.php

When I execute the first script as following : 

```
 docker exec -it dolibarr php /var/www/htdocs/install/upgrade.php 9.0.4 10.0.0
```

I'm getting the following error : 

> PHP Warning:  require_once(../filefunc.inc.php): failed to open stream: No such file or directory in /var/www/html/install/inc.php on line 31
> PHP Fatal error:  require_once(): Failed opening required '../filefunc.inc.php' (include_path='.:/usr/local/lib/php') in /var/www/html/install/inc.php on line 31

Same happened if I use the folder `html` instead of `htdocs`

It's working fine If I upgrade through the browser

**Comment by tuxgasy** [comment]
The current directory must be /var/www/htdocs/install before run script.

The docker image supports now database migration (see https://github.com/tuxgasy/docker-dolibarr#upgrading-version-and-migrating-db)

**Comment by mathieupotier** [comment]
Just in time it seems @tuxgasy ^_^
