### ISSUE TITLE
How to update using CLI

### ISSUE THREAD

**Issue by vipera7** [tuxgasy/docker-dolibarr#27]
Hello,

I'm trying to update my Dolibarr using CLI. I have a small question about it. I know I have to run the script **upgrade.php**, **upgrade2.php**, **step5.php** for upgrading. For exemple I want to go from version 6.0.8 and install the latest version (12.0.1). I know I have to make 6 to 7, 7 to 8, 8 to 9, 9 to 10, 10 to 11 and 11 to 12. But do I have to use :

`php upgrade.php 6.0.8 7.0.0`

or

`php upgrade.php 6.0.0 7.0.0`

And on the last step

`php upgrade.php 11.0.0 12.0.2`

or

`php upgrade.php 11.0.0 12.0.0`

In the doc, it says that z must be 0 but I don't know if oldz must be 0 too

https://wiki.dolibarr.org/index.php/Installation_-_Upgrade

Thanks for any help

**Comment by mathieupotier** [comment]
Hi @vipera7 ,

Basically the image can now handle this kind of migration automatically as described in [Readme](https://github.com/tuxgasy/docker-dolibarr#upgrading-version-and-migrating-db) and don't forget to delete the lock file to trigger this process.

Tell me / suggest change if it's not clear enough.

Those steps are run with the correct parameters using the current Dolibarr version and the version stored on the Database.
It also backup the db before migrating...
So you won't have to run anything on your own.

You can inspect the script for migrating DB here : https://github.com/tuxgasy/docker-dolibarr/blob/master/docker-run.sh#L116

If your not confident enough with this automation, you still can perform the manual update via Web UI

**Comment by vipera7** [comment]
Thanks for the reply ! @mathieupotier 
Well I deleted the install.lock and added `DOLI_INSTALL_AUTO=1`, but I can't login to my dolibarr instance now. Here is the full error I'm getting from the login page: 

> Unknown column 'u.personal_email' in 'field list'

I don't think my service creation is wrong : 

`docker service create --replicas 2 -d --name Dolibarr_swarm -e DOLI_INSTALL_AUTO=1 -e DOLI_DB_HOST="192.168.0.2" -e DOLI_DB_USER="admin" -e DOLI_DB_PASSWORD="root" -e DOLI_DB_NAME="dolibarr" -p ${port}:80 --mount type=volume,dst=/var/www/documents,volume-driver=local,volume-opt=type=nfs,\"volume-opt=o=nfsvers=4,addr=${nfs_server}\",volume-opt=device=:$documents_path --mount type=volume,dst=/var/www/htdocs/custom,volume-driver=local,volume-opt=type=nfs,\"volume-opt=o=nfsvers=4,addr=${nfs_server}\",volume-opt=device=:$custom_path tuxgasy/dolibarr:latest`


Here is my docker logs : 
```
usermod: no changes
[INIT] => update PHP Config ...
[INIT] => update Dolibarr Config ...
[INIT] => update ownership for file in Dolibarr Config ...
[INIT] => update ownership for files in /var/www/documents ...
Current Version is : 12.0.2
Last installed Version is : 6.0.8
Schema update is required ...
Dumping Database into /var/www/documents/dump.sql ...
Dump done ... Starting Migration ...
Migration successful ... Enjoy !!
AH00557: apache2: apr_sockaddr_info_get() failed for 09adf2f19048
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.0.1. Set the 'ServerName' directive globally to suppress this message
AH00557: apache2: apr_sockaddr_info_get() failed for 09adf2f19048
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.0.1. Set the 'ServerName' directive globally to suppress this message
[Tue Sep 01 07:31:42.275987 2020] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.38 (Debian) PHP/7.4.8 configured -- resuming normal operations
[Tue Sep 01 07:31:42.278004 2020] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
.
.
.
```

It work well with my custom script.
Maybe it doens't support docker services (swarm)

**Comment by mathieupotier** [comment]
The documentation from Dolibarr, seems not requiring to go through all majors ... so I did'nt do it that way ...

Maybe the swarm mode could be an issue ... as it could try to do migration twice ...
Suggest to : 
 - restore DB
 - try the migration with replicas to 1 in order to avoid this possible mess ...

As you're coming from far way version to latest ... It could be safer to just pass through web-ui upgrade :
DOLI_INSTALL_AUTO=1 and remove lock file and after got throught the `/install` uri

**Comment by vipera7** [comment]
Oh okay, didn't know that. In the web installer it said that we need to pass throught all major version.
I tried using replicas 1 and I'm still getting the error. I want to automate the update process. I'm able to update doing the following : 
```
docker service rm Dolibarr_swarm
docker service create --replicas2 ...  tuxgasy/dolibarr:latest
sleep 10
for i in `seq 1 400`;
do
    if nc -w1 -z $address $port; then
        break
        echo "Instance is UP"
   else
        echo "Waiting"
   fi
   sleep 1
done

if [ -e /nfs/Dolibarr_swarm/documents/install.lock ]; then
        rm -Rf /nfs/Dolibarr_swarm/documents/install.lock
fi

INSTALLED_VERSION=$(mysql -u Dolibarr_"$id_service" -p"$dbdolpass" -h "$dbhost" Dolibarr_"$id_service" -rN -e "SELECT Q.LAST_INSTALLED_VERSION FROM (SELECT INET_ATON(CONCAT(value, REPEAT('.0', 3 - CHAR_LENGTH(value) + CHAR_LENGTH(REPLACE(value, '.', ''))))) as VERSION_ATON, value as LAST_INSTALLED_VERSION FROM llx_const WHERE name IN ('MAIN_VERSION_LAST_INSTALL', 'MAIN_VERSION_LAST_UPGRADE') and entity=0) Q ORDER BY VERSION_ATON DESC LIMIT 1")
old_val=${INSTALLED_VERSION:position:1}
container_id=$(docker ps -aqf "name=Dolibarr_swarm")
for i in `seq $old_val 12`
do
    if [[ "$old_val" -eq "$i" ]]; then
        docker exec "$container_id" bash -c "cd /var/www/htdocs/install ; php upgrade.php $INSTALLED_VERSION $((i+1)).0.0"
        docker exec "$container_id" bash -c "cd /var/www/htdocs/install ; php upgrade2.php $INSTALLED_VERSION $((i+1)).0.0"
        docker exec "$container_id" bash -c "cd /var/www/htdocs/install ; php step5.php $INSTALLED_VERSION $((i+1)).0.0"
    elif [[ $((i+1)) != $((new_dolibarr_version+1)) ]]; then
        docker exec "$container_id" bash -c "cd /var/www/htdocs/install ; php upgrade.php ${i}.0.0 $((i+1)).0.0"
        docker exec "$container_id" bash -c "cd /var/www/htdocs/install ; php upgrade2.php ${i}.0.0 $((i+1)).0.0"
        docker exec "$container_id" bash -c "cd /var/www/htdocs/install ; php step5.php ${i}.0.0 $((i+1)).0.0"
    fi
done
echo > /nfs/Dolibarr_swarm/documents/install.lock
chmod 444 /nfs/Dolibarr_swarm/documents/install.lock
```

**Comment by mathieupotier** [comment]
Hi, seems legit, you can contribute to this repo by editing the docker-run.sh script to deal with a looped version upgrade...

**Comment by mathieupotier** [comment]
@tuxgasy I think that using the standard Dolibarr update process web side is a good option, I'm afraid that it could lead to over-engineered stuff in the init-script : what do you think about it ?

**Comment by tuxgasy** [comment]
If there is a bug in the update script of Dolibarr, I think it must be fixed on Dolibarr repository.

**Comment by vipera7** [comment]
Why do you think there is a bug in the update script ? In the doc of Dolibarr, you need to go through all major versions.

v9 -> v10 -> v11
and not
v9 -> v11

**Comment by tuxgasy** [comment]
Hi all
I think we can close this issue now.
If need, please open a new issue or PR.
