### ISSUE TITLE
Upgrade de la version du container

### ISSUE THREAD

**Issue by mxz-redhot** [tuxgasy/docker-dolibarr#3]
Bonjour,
Est-ce possible de faire une Maj de la version du dolibarr installée dans le container?

J'ai vu le script update.sh, mais j'ai plus l'impression que c'est pour faire un update des versions installables.

Merci d'avance!

**Comment by tuxgasy** [comment]
Bonjour,

C'est tout à fait possible de faire une maj de Dolibarr mais manuellement.
Mais le plus simple de mettre à jour l'image docker utilisé. Étant donnée que la base de donnée est sur un autre container, il n'y a pas de perte de données si en plus tu montes le dossier document en tant que volume.
