### ISSUE TITLE
REST Api module not working

### ISSUE THREAD

**Issue by R0dri** [tuxgasy/docker-dolibarr#33]
It works with some routes, but the main route `localhost/api/inedx.php/explorer` is not working. This error appears.
> API not found (failed to include API file)

If I make a GET request to /status It works. 

I found this issue on the [main repo](https://github.com/Dolibarr/dolibarr/issues/14279#issuecomment-664828439) that apparently was fixed, is this build a previous version?

I used the docker build from the main site and I have no issues there. I guess I can develop with the "development" docker build and use this when I am done with integrations. But this does not seem too good of a solution either.

**Comment by mathieupotier** [comment]
hi,

12.0.4 has not been build yet on this repository, you can open a PR following the readme to do so.
for reference : https://github.com/tuxgasy/docker-dolibarr/blob/master/CONTRIBUTING.md

**Comment by mathieupotier** [comment]
Does lastest releases fix this now @R0dri ?

**Comment by R0dri** [comment]
I can't really say. I've stopped using the the app since. I've decided to migrate to a different solution. Unfortunately I had an accidental deletion of the docker volume while I was migrating so I can't really test it right now. I'm sorry for that.

**Comment by mathieupotier** [comment]
@tuxgasy I think this issue could be closed safely.
