### ISSUE TITLE
use bcrypt instead of md5

### ISSUE THREAD

**Issue by DanielRuf** [tuxgasy/docker-dolibarr#35]
https://github.com/tuxgasy/docker-dolibarr/blob/81bf31ccc5a3d9f6bd72ec03ec4a2ef9d3821a05/images/12.0.3-php7.4/docker-run.sh#L105-L106

**Comment by mathieupotier** [comment]
Hi, I suggest you to open a PR to make this change.

**Comment by DanielRuf** [comment]
Thanks, will do when I find some time.

It also seems password hashing is not enabled by default but this is probably a bug in dolibarr itself and its installer.

**Comment by DanielRuf** [comment]
I'm currently not sure what solution is the best. It seems for this to work the htpasswd binary from Apache 2.4+ could be an option.

See https://unix.stackexchange.com/questions/307994/compute-bcrypt-hash-from-command-line and https://www.ask-sheldon.com/create-a-bcrypt-hash-on-commandline/

What do you think?

**Comment by mathieupotier** [comment]
I'm not sure either that we can do this now with Dolibarr, if password we set is not usable directly by frontend it will messup new installs ... have to test the solution before (with all Dolibarr version in this repo)
