### ISSUE TITLE
IMAP function not found

### ISSUE THREAD

**Issue by AndresJ551** [tuxgasy/docker-dolibarr#37]
Hello and happy new year!

I'm trying to setup the email collector, but it's presenting the error "IMAP functions not available on your PHPFailed to open IMAP connection".
I have:

- apt-get update & apt-get upgrade the container.
- apt-get install php7.3-imap
- apt-get install php-imap

All without success.
Could you guide me on the solution?

Thanks!

**Comment by AndresJ551** [comment]
Hey there, I think I found the solution:
Previously you need the dev libraries:
RUN apt-get update && apt-get install -y libc-client-dev libkrb5-dev && rm -r /var/lib/apt/lists/*
And then compile PHP for the libary IMAP:
RUN docker-php-ext-configure imap --with-kerberos --with-imap-ssl && docker-php-ext-install imap

As discused on https://stackoverflow.com/a/38526260

**Comment by mathieupotier** [comment]
@tuxgasy I think that it could be an interesting improvement to this image.
I could have the same interest in order to open a feature about mail hooks in Dolibarr... https://wiki.dolibarr.org/index.php?title=Module_EMail_Collector

**Comment by tuxgasy** [comment]
Why not !

**Comment by mathieupotier** [comment]
@tuxgasy Assign this issue to me, I'll do this before the end of april.

**Comment by mathieupotier** [comment]
@AndresJ551 does it fit your needs ?
@tuxgasy I think we can close this ...

**Comment by AndresJ551** [comment]
@mathieupotier that is perfect. Thank you!
