### ISSUE TITLE
Can't start the container

### ISSUE THREAD

**Issue by felizycontento** [tuxgasy/docker-dolibarr#39]
I allways get the following error

ERROR: The Compose file './docker-compose.yml' is invalid because: Unsupported config option for services: 'mariadb'

**Comment by mathieupotier** [comment]
hi @felizycontento,

We'll need to see your docker-compose file to help ... for sure mariadb is not a valid option for a service in a docker-compose file ^_^

**Comment by DanielBanobreDopico** [comment]
I have solved this issue by adding this line:
```yaml
version: "3.7"
```
in the top of docker-compose.yml file.

**Comment by mathieupotier** [comment]
@tuxgasy I think this issue could be closed safely.
