### ISSUE TITLE
migration from real server to docker 

### ISSUE THREAD

**Issue by walmins** [tuxgasy/docker-dolibarr#4]
Bonjour et merci pour ton travail.
Pour migrer une version depuis un vrais serveur vers la version docker tu pense que c'est possible juste d'importer la base de données et faire une MAJ?

Merci

**Comment by tuxgasy** [comment]
Bonjour,

C'est tout à fait possible.

**Comment by fpeyraud** [comment]
Hello
J'ai effectué cette opération il y a quelques semaines en passant d'une version standard en 4.0.x vers la version en 6.0.2. La mise à jour de la base a bien fonctionné à une exception près sur des valeurs par défaut dans la table llx_accounting_account concernant la colonne account_parent, mais en contrôlant manuellement dans la base, j'ai pu sauter l'étape et enchaîner sur les autres migrations sans soucis fonctionnel pour l'instant :)
