### ISSUE TITLE
ADD Volumen /var/www/html

### ISSUE THREAD

**Issue by davidpebe78** [tuxgasy/docker-dolibarr#47]
I need to add a volume to the image, / var / www / html. I have tried to do it through Dokerfile, but I could not, because I am a bit of a newbie.
If you could add it, I would appreciate it.
Thanks a lot.

**Comment by mathieupotier** [comment]
I don't think such a volmume is necessary, image has volumes to documents ...
What is that for ?
If you really need it, docker will not prevent you to mount host dir into this one, but you'll probably loose the interest of using this images in fact...

**Comment by mathieupotier** [comment]
@tuxgasy I think you can close this one.

**Comment by freechelmi** [comment]
Then could be reopen this issue ? 

If we add the /var/www/html volume in the image , is this a problem for some users ?

**Comment by mathieupotier** [comment]
Hi @freechelmi,
You can mount this path into your docker ... but in this image, it's attached to a dedicated Dolibarr version and this will go against this...
I'll check the documentation from Dolibarr to check if there is a solution available, but I'm not confident by mounting the all /var/www/html in this image (a simple PHP/apache image could do the trick for you)

**Comment by mathieupotier** [comment]
@freechelmi I opened a feature request related to this : I probably found the solution without mounting the whole /var/www/html directory ...
https://github.com/tuxgasy/docker-dolibarr/issues/68

**Comment by freechelmi** [comment]
Thanks my problem was  the cyberoffice plugin who wants to be in htdocs , but I'd better to it own dedicated volume to make upgrade possible easily.

So I would finally propose to keeps this issue closed
