### ISSUE TITLE
htdocs volume

### ISSUE THREAD

**Issue by walmins** [tuxgasy/docker-dolibarr#5]
Bonjour sais tu s'il te plait comment faire pour mettre le dossier /var/ww dans un autre dossier dans docker?

car je n'arrive pas avec: 
volumes:
       - /srv/dockers/web/compta/www:/var/www

j'ai toujours des erreurs.

Merci
V

**Comment by tuxgasy** [comment]
Bonjour,

Ça a l'air correct. Tu as quoi comme erreurs ?

**Comment by walmins** [comment]
me semble qu'il arrive a copier un truc :-(
![image](https://user-images.githubusercontent.com/7791828/30544851-26e9ab68-9c88-11e7-883f-9ba23da05a05.png)

**Comment by tuxgasy** [comment]
Ah oui, il faut plutôt mettre dans le dossier /var/www/html ou sinon, il faut adapter le script docker-run.sh

**Comment by walmins** [comment]
DOLI_URL_ROOT: 'http://0.0.0.0'
       PHP_INI_DATE_TIMEZONE: 'Europe/Paris'
       DOLI_INSTALL_AUTO: 1
     
     volumes:
       - /MY_PATH/www:/var/www

**Comment by walmins** [comment]
mais pourquoi tu

**Comment by walmins** [comment]
mais pourquoi tu fais le lien symbolique ? 
j'ai deja tester avec /var/www/html :-(

**Comment by walmins** [comment]
j'ai une impression qu'il ne recharge pas les fichiers dans le dossier...le dossier reste toujours vide.

Merci

**Comment by tuxgasy** [comment]
Il faut mettre :

     volumes:
       - /MY_PATH/www:/var/www/html

Il faut éventuellement supprimer la partie récupération de Dolibarr dans le Dockerfile.
Le lien symbolique permet d'utiliser les fichiers de scripts (le cron par exemple).
Tu peux t'inspirer de ce que j'ai intégré directement dans [les sources de Dolibarr](https://github.com/Dolibarr/dolibarr/tree/develop/build/docker).

**Comment by walmins** [comment]
si je comprends bien c'est cette parti qu'il ne le fait pas :-(
# Get Dolibarr
ADD https://github.com/Dolibarr/dolibarr/archive/${DOLI_VERSION}.zip /tmp/dolibarr.zip
RUN unzip -q /tmp/dolibarr.zip -d /tmp/dolibarr
RUN cp -r /tmp/dolibarr/dolibarr-${DOLI_VERSION}/htdocs/* /var/www/html/ && ln -s /var/www/html /var/www/htdocs
RUN cp -r /tmp/dolibarr/dolibarr-${DOLI_VERSION}/scripts /var/www/
RUN rm -rf /tmp/dolibarr

**Comment by walmins** [comment]
car quand je me log sur le docker il y a rien dans ces dossier, en revanche si je ne force pas le volume alors les fichiers sont bien copie, donc je ne sais pas comment lui dire de telechatge le dossier dans mon volume..
Merci

**Comment by walmins** [comment]
finalement j'ai abandonné l'idée, je suis resté sur
nginx+dolibarr+let'sencrypt

merci pour ton temp

Le 18 septembre 2017 à 21:31, Garcia MICHEL <notifications@github.com> a
écrit :

**Comment by antoinm** [comment]
Est ce que quelqu'un a trouvé un moyen? Je fais face au même problème et n'arrive pas à le solutionner.

**Comment by antoinm** [comment]
Ok, j'ai trouvé! 

La copie des fichiers ne s'effectue pas car le lien symbolique ne peut pas être créé : `failed to create symbolic link file exists`, il suffit donc de forcer la création du lien symbolique en modifiant le Dockerfile

**Comment by jokodi** [comment]
> you just have to force the creation of the symbolic link by modifying the Dockerfile

Hello, i'm running into the same issue. Could you elaborate a bit more on your solution and how to do this? Thank you!

**Comment by antoinm** [comment]
@jokodi when you create the symbolic link using the `ln` command, just pass the `-f` (or `--force`) argument to force the creation of the symbolic link
