### ISSUE TITLE
Update broke

### ISSUE THREAD

**Issue by SecT0uch** [tuxgasy/docker-dolibarr#52]
I just updated and moved the volumes and now Dolibarr seems broken.

When I try to login now I get the following error:
> Table 'dolibarr.llx_user' doesn't exist

I have `DOLI_INSTALL_AUTO=1`

Here are the steps I did:
* docker-compose pull && docker-compose up -d
* I had the message saying to rm install.lock
* I couldn't find the volumes because of a typo in my `docker-compose.yml`. I had `dolibarr-docs:/var/www/documents` and `mysql-data:/var/lib/mysql` instead of (for my setup) `./dolibarr-docs:/var/www/documents` and `./mysql-data:/var/lib/mysql`.
* I ran  `mv /var/lib/docker/volumes/dolibarr_dolibarr-docs /opt/Dolibarr/dolibarr-docs` and `mv /var/lib/docker/volumes/dolibarr_mysql-data /opt/Dolibarr/mysql-data` and adapted the `docker-compose.yml`  to fit the changes.
* Finally, I ran `rm /opt/Dolibarr/dolibarr-docs/_data/install.lock` and `docker-compose up -d`

My guess is I deleted the install.lock before the migration could succeed.

**Comment by mathieupotier** [comment]
Hi @SecT0uch,

Do you stopped your docker stack before moving files ? I know that MariaDB ios locking files when running...
Basically you've done some operation that are quite advanced in docker such as moving volumes ^_^

I suggested that you check that your DB files have been successfully moved (with MariaDB stopped) and also check files permission ...

I know that the auto migration process is not covering all angles. Consider migrating from a version to another using the dolibarr webinterface.

Regards,
Mathieu

**Comment by mathieupotier** [comment]
Just thought about it, and I can suggest that you create a brand new instance of DB and restoring the most up-to-date backup.
Don't forget to fix the dolibarr version according to your backuped version.
ie dolibarr version is in the filename of your DB backup : `mysqldump_dolibarr_13.0.3_202107220030.sql.gz`

**Comment by SecT0uch** [comment]
Just reinstalled from Scratch. Didn't manage to recover the (few) data.
