### ISSUE TITLE
Env DOLI_DB_HOST doesn't like domain names

### ISSUE THREAD

**Issue by DualBandWiFi** [tuxgasy/docker-dolibarr#53]
Hello maintainer :)

It's not a deal breaker, but I've noticed that the env doesn't likes domain names. It didn't even reach my DNS server to resolve it.
Noticed it as the DB was 0B and the log was stuck on "waiting for sql db to be up" or similar.

As soon as I redeployed it with the ip address it worked flawlessly.
Thanks for you labor :)

Regards,
Alan.

**Comment by mathieupotier** [comment]
Hi @DualBandWiFi ,

Have you checked that your docker is able to request DNS ?

Can you please attach here the docker-compose you're refering to ?

Regards,
Mathieu

**Comment by DualBandWiFi** [comment]
Hi Mathieu :)
I'm not using docker-compose, instead I'm managing all my docker hosts with portainer.
The host itself resolves dns, as I have everything pointing to my stuff using DNS, I don't like using fixed ip addreses (I'm just a weird sysadmin).

It seems it's not the env, because I triggered the manual installation (via web), by deleting the conf inside the /var/www/html/conf/ folder, and it hang when I tried to install using a domain name.
I can't check if the container resolves dns because I don't have ping or any other tool inside the container.

Regards,
Alan.

**Comment by mathieupotier** [comment]
Hi @DualBandWiFi,

I don't think that is a problem from this image, as DNS resolution is working in my implemention (docker-compose), maybe a setup in your portainer agent should fix this... I cannot help on this topic, as I started using portainer but revert back to issues with network bindings ... maybe related ^_^

> `I can't check if the container resolves dns because I don't have ping or any other tool inside the container.`

I just can suggest to add this by extending this image into your own one, basically it's a simple Debian image, so should be easy to add.

Regards

**Comment by tuxgasy** [comment]
I think we can close this issue.
If need, please open a new issue/PR.
