### ISSUE TITLE
Peristent Data

### ISSUE THREAD

**Issue by Thom087** [tuxgasy/docker-dolibarr#59]
I am trying to mount the volumes for persistence:
version: "3"
services:
    mariadb:
        image: mariadb:latest
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: dolibarr
        restart: always
        volumes:
            - ./db:/var/lib/mysql
    web:
        image: tuxgasy/dolibarr
        environment:
            DOLI_DB_HOST: mariadb
            DOLI_DB_USER: root
            DOLI_DB_PASSWORD: root
            DOLI_DB_NAME: dolibarr
            DOLI_URL_ROOT: 'http://0.0.0.0'
        links:
            - mariadb
        volumes:
            - ./dolibarr_html:/var/www/html
            - ./dolibarr_docs:/var/www/documents

        
The directory of dolibarr_html / dolibarr_docs is empty and if I try to connect to http://0.0.0.0 the log says the following:

> web_1      | [Fri Aug 20 08:05:22.906246 2021] [autoindex:error] [pid 61] [client 172.24.0.2:33478] AH01276: Cannot serve directory /var/www/html/: No matching DirectoryIndex (index.php,index.html) found, and server-generated directory index forbidden by Options directive`

**Comment by mathieupotier** [comment]
Hi @Thom087,

When you mount local host directory into a docker, the host content take priority over the docker container ...
Is your directory ./dolibarr_html empty ?
Basically I don't think you need to map the /var/www/html volume... except if you have a full specific version on host...

Check out this example ...
https://github.com/tuxgasy/docker-dolibarr/blob/master/examples/with-mysql/docker-compose.yml
