### ISSUE TITLE
Problem expose volumes

### ISSUE THREAD

**Issue by didierbroska** [tuxgasy/docker-dolibarr#6]
Bonjour, merci pour votre travail tout d'abord.
Je voudrais dans un docker-compose exposé le volume /var/www de votre conteneur, mais lors de la mise en 'UP' de la composition, celui-ci me sort une erreur et ne veut donc pas démarrer.
Auriez vous une astuce à me conseiller pour effectuer cela ?

Merci d'avance.

**Comment by tuxgasy** [comment]
Bonsoir,

Pouvez-vous publier votre fichier de docker-compose  avec le message d'erreur ?

**Comment by didierbroska** [comment]
Bonjour, ma configuration est :
- Docker Community Edition macOS v17.09.1-ce-mac42 [Stable]
- Container : tuxgasy/dolibarr:latest
- Container : mariadb:latest

_J'utilise un trio de conteneur pour autogénérer les templates pour le proxy nginx, un proxy nginx et un récupérateur de certificat Let's Encrypt._
_J'ai essayé avec ou sans. Je précise seulement._

J'essaie donc de monté la ressource **/var/www** du conteneur quelque part dans ma **/home**, afin de pouvoir remplacer la configuration initial par ma configuration qui provient d'un serveur **non dockerized**.

Tout d'abord voici mon fichier docker-compose.yml :
`version: '3'

services:
   db:
     container_name: mariadb
     image: mariadb
     restart: unless-stopped
     volumes:
       - ~/path/to/mariadb:/var/lib/mysql
     environment:
       MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWD}
       MYSQL_DATABASE: ${DB_NAME}
       MYSQL_USER: ${DB_USER}
       MYSQL_PASSWORD: ${DB_PASSWD}

   dolibarr:
     depends_on:
       - db
     container_name: dolibarr
     image: tuxgasy/dolibarr
     restart: unless-stopped
     ports:
       - 8080:80
     environment:
       DOLI_DB_HOST: db
       DOLI_DB_USER: ${DB_USER}
       DOLI_DB_PASSWORD: ${DB_PASSWD}
       DOLI_DB_NAME: ${DB_NAME}
       DOLI_URL_ROOT: ${DOMAINS}
       PHP_INI_DATE_TIMEZONE: Europe/Paris
       VIRTUAL_HOST: ${DOMAINS}                                       # Champ proxy
       LETSENCRYPT_HOST: ${DOMAINS}                             # Champ Let's Encrypt
       LETSENCRYPT_EMAIL:  ${LETSENCRYPT_EMAIL}      # Champ Let's Encrypt
     volumes:
       - ~/path/to/dolibarr:/var/www

networks:
    default:
       external:
         name: ${NETWORK}
`

Ainsi lorsque je lance cette configuration, il bloque à priori à cause du montage de ressource, code erreur :

> ERROR: for dolibarr  Cannot start service dolibarr: oci runtime error: container_linux.go:265: starting container process caused "chdir to cwd (\"/var/www/html\") set in config.json failed: no such file or directory"

> ERROR: for dolibarr  Cannot start service dolibarr: oci runtime error: container_linux.go:265: starting container process caused "chdir to cwd (\"/var/www/html\") set in config.json failed: no such file or directory"

>ERROR: Encountered errors while bringing up the project.

Voilà, j'espère être assez précis. Merci à bientôt.

**Comment by tuxgasy** [comment]
Ok, je vois. En fait, en montant le dossier /var/www, le contenu dans le docker est remplacé par le contenu du dossier source /path/to/dolibarr.
Si votre but est d'avoir accès à la configuration, je vous conseille de monter plutôt le dossier /var/www/html/conf.
Si vous souhaitez accéder à la source de Dolibarr, j'ai intégré dans Dolibarr un dockerfile plus adapté à cela. [Ça a été intégré à partir de la version 6](https://github.com/Dolibarr/dolibarr/tree/develop/build/docker).

**Comment by didierbroska** [comment]
Merci, je vais regarder cela !!!!

Car en faite j'ai plusieurs serveurs qui tournent et je veux aussi pouvoir faire une syncro de leurs données ( factures, devis et autres datas). 

Mais aussi faire des ajouts de modules simplement sans avoir à lancer de commander docker pour ajouter des éléments.

Je met en place ce système car mon serveurs est la ou mes app sont et j'utilise des fois mes applications sans avoir de connexion internet.

Je ne sais pas si je suis clair.

Mais en tout cas merci pour le lien, je vais voir cela avec attention.
