### ISSUE TITLE
README on docker hub not sync with github readme

### ISSUE THREAD

**Issue by mathieupotier** [tuxgasy/docker-dolibarr#61]
Hi, I noticed that the docker hub readme is no more synced with the github Readme.

https://hub.docker.com/r/tuxgasy/dolibarr/

**Comment by mathieupotier** [comment]
Seen on searching on the net :

https://newbedev.com/how-to-push-a-docker-image-with-readme-file-to-docker-hub

```
docker run -v $PWD:/workspace \
      -e DOCKERHUB_USERNAME='user1' \
      -e DOCKERHUB_PASSWORD='xxxxx' \
      -e DOCKERHUB_REPOSITORY='my-docker-image' \
      -e README_FILEPATH='/workspace/README.md' \
      peterevans/dockerhub-description:2.1.0
```

I'm not familiar with travis CI ... but probably adding a deploy step running this docker image

**Comment by tuxgasy** [comment]
Ok I will test it.
