### ISSUE TITLE
drop support for PHP5 based images

### ISSUE THREAD

**Issue by mathieupotier** [tuxgasy/docker-dolibarr#62]
What do you think about it @tuxgasy ?
It will reduce disk usage on docker hub, and also avoid confusion ... PHP 5 is no more supported (could lead to security vulnerability).

**Comment by tuxgasy** [comment]
Yes we can remove PHP5 support now.

**Comment by mathieupotier** [comment]
https://github.com/tuxgasy/docker-dolibarr/pull/64

**Comment by mathieupotier** [comment]
@tuxgasy can close this
