### ISSUE TITLE
Feature Request - Adding the capacity to install thrid party plugin into these containers

### ISSUE THREAD

**Issue by mathieupotier** [tuxgasy/docker-dolibarr#68]
Add a volume pointing to /custom directory, enabling the installation of third party plugins from end-user.

https://wiki.dolibarr.org/index.php?title=Module_File_Manager#Installation

**Comment by freechelmi** [comment]
Thanks this will be very useful

**Comment by mathieupotier** [comment]
I'll test this this week (tonight or tomorrow) PR should follow ... will probably be available on the 14.0.3 version next week, depending on availability to merge from @tuxgasy ^_^

**Comment by mathieupotier** [comment]
https://github.com/tuxgasy/docker-dolibarr/pull/71
