### ISSUE TITLE
docker-compose file

### ISSUE THREAD

**Issue by useramuser** [tuxgasy/docker-dolibarr#7]
Hi, I have the following problem:

I only created the docker-compose file on a test server. I copied nothing else there. (should I?)

When I try to run your docker-compose up I get this error:

root@dolibarr:/home# docker-compose up

ERROR: yaml.scanner.ScannerError: mapping values are not allowed here
  in "./docker-compose.yml", line 14, column 28

I am using Docker version 17.12.0-ce

Is it possible, that the syntax is wrong?

Thanks :-)

**Comment by tuxgasy** [comment]
Hi,

Without seeing you file, I can't help you.

**Comment by useramuser** [comment]
mariadb:
    image: mariadb:latest
    environment:
        MYSQL_ROOT_PASSWORD: rootdolibarr$%
        MYSQL_DATABASE: dolibarr
web:
    image: tuxgasy/dolibarr
    environment:
        DOLI_DB_HOST: mariadb
        DOLI_DB_USER: root
        DOLI_DB_PASSWORD: rootdolibarr$%
        DOLI_DB_NAME: dolibarr
        DOLI_URL_ROOT: 'https://0.0.0.0';
        PHP_INI_DATE_TIMEZONE: 'Europe/Paris'
    ports:
        - "80:80"
        - "443:443"
    links:
        - mariadb

**Comment by useramuser** [comment]
`mariadb:
    image: mariadb:latest
    environment:
        MYSQL_ROOT_PASSWORD: rootdolibarr$%
        MYSQL_DATABASE: dolibarr
web:
    image: tuxgasy/dolibarr
    environment:
        DOLI_DB_HOST: mariadb
        DOLI_DB_USER: root
        DOLI_DB_PASSWORD: rootdolibarr$%
        DOLI_DB_NAME: dolibarr
        DOLI_URL_ROOT: 'https://0.0.0.0';
        PHP_INI_DATE_TIMEZONE: 'Europe/Paris'
    ports:
        - "80:80"
        - "443:443"
    links:
        - mariadb
`

**Comment by useramuser** [comment]
mariadb:
    image: mariadb:latest
    environment:
        MYSQL_ROOT_PASSWORD: rootdolibarr$%
        MYSQL_DATABASE: dolibarr
web:
    image: tuxgasy/dolibarr
    environment:
        DOLI_DB_HOST: mariadb
        DOLI_DB_USER: root
        DOLI_DB_PASSWORD: rootdolibarr$%
        DOLI_DB_NAME: dolibarr
        DOLI_URL_ROOT: 'https://0.0.0.0';
        PHP_INI_DATE_TIMEZONE: 'Europe/Paris'
    ports:
        - "80:80"
        - "443:443"
    links:
        - mariadb

**Comment by useramuser** [comment]
I have the indentation, just like in your file, but it is not showing in this editor...

**Comment by tuxgasy** [comment]
Try to remove the charater ; on DOLI_URL_ROOT var

**Comment by useramuser** [comment]
Sorry, this is the file I used in the last try:

mariadb:
    image: mariadb:latest
    
        MYSQL_ROOT_PASSWORD: rootdolibarr$%
        MYSQL_DATABASE: dolibarr

web:
    build: ./images/$DOLI_VERSION
    
        DOLI_DB_HOST: mariadb
        DOLI_DB_USER: root
        DOLI_DB_PASSWORD: rootdolibarr$%
        DOLI_DB_NAME: dolibarr
        DOLI_URL_ROOT: 'https://0.0.0.0'
        WWW_USER_ID: 1000
        WWW_GROUP_ID: 1000
    ports:
        - "80:80"
        - "443:443"
    links:
- mariadb

**Comment by useramuser** [comment]
In this one there was no ; sign

**Comment by useramuser** [comment]
mariadb:
    image: mariadb:latest
    
        MYSQL_ROOT_PASSWORD: rootdolibarr$%
        MYSQL_DATABASE: dolibarr
web:
    build: ./images/$DOLI_VERSION
    
        DOLI_DB_HOST: mariadb
        DOLI_DB_USER: root
        DOLI_DB_PASSWORD: rootdolibarr$%
        DOLI_DB_NAME: dolibarr
        DOLI_URL_ROOT: 'https://0.0.0.0'
        WWW_USER_ID: 1000
        WWW_GROUP_ID: 1000
    ports:
        - "80:80"
        - "443:443"
    links:
       - mariadb

**Comment by tuxgasy** [comment]
It's missing the environment key.

**Comment by useramuser** [comment]
Yeah, thanks man. It kind of worked now.

**Comment by useramuser** [comment]
The installation now always stops at:
(I tried all the images)
It gives a php5-mysql error, even when the selected image is supposed to be php7.

Do you have an idea what goes wrong here?


`Package php5-mysql is a virtual package provided by:
  php5-mysqlnd 5.6.33+dfsg-0+deb8u1 [Not candidate version]
  php5-mysqlnd 5.6.30+dfsg-0+deb8u1 [Not candidate version]

E: Package 'php5-mysql' has no installation candidate
ERROR: Service 'web' failed to build: The command '/bin/sh -c apt-get update -q && apt-get upgrade -yq  && apt-get install -yq          libpng12-dev            libjpeg-dev     php5-mysql     libxml2-dev     mysql-client                 unzip   && rm -rf /var/lib/apt/lists/*  && docker-php-ext-configure gd --with-png-dir=/usr --with-jpeg-dir=/usr         && docker-php-ext-install gd mysqli soap zip' returned a non-zero code: 100`

**Comment by querplis** [comment]
@useramuser 
if you are using 6.0.4-php7.1/Dockerfile
remove 27 line
