### ISSUE TITLE
Dolibarr on qnap container station 

### ISSUE THREAD

**Issue by henne2** [tuxgasy/docker-dolibarr#77]
Hello, I would like to use the docker image on a qnap container station. 
When I start the docker I get the following error : 
"  standard_init_linux.go:228: exec user process caused: exec format error  "

It is the only thing , that appears.  What can be done to avoid this and run the docker?

I am thankfull  for all sugestions. :+1:

**Comment by henne2** [comment]
@tuxgasy do you have an idea how to fix the  error :
" standard_init_linux.go:228: exec user process caused: exec format error " ?
Many Greetings

**Comment by tuxgasy** [comment]
No idea! Sorry.

**Comment by tuxgasy** [comment]
Hi @henne2 

If your qnap is running under ARM architecture, it should work now.

**Comment by henne2** [comment]
Hey tuxgasy ,  it is running an ARM .   Many thanks I will try it out .  If it really works , I can fund you 50€.
