### ISSUE TITLE
Build error libpng12-dev

### ISSUE THREAD

**Issue by waveguerilla** [tuxgasy/docker-dolibarr#8]
Hi,

I have a build error :

`Package libpng12-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libpng12-dev' has no installation candidate
ERROR: Service 'dolibarr' failed to build: The command '/bin/sh -c apt-get update -q && apt-get upgrade -yq 	&& apt-get install -yq 		libpng12-dev 		libjpeg-dev     libxml2-dev     mysql-client 		unzip 	&& rm -rf /var/lib/apt/lists/* 	&& docker-php-ext-configure gd --with-png-dir=/usr --with-jpeg-dir=/usr 	&& docker-php-ext-install mysqli pdo pdo_mysql gd soap zip' returned a non-zero code: 100`

**Comment by tuxgasy** [comment]
Hi,

With which php version ? dolibarr version ?

**Comment by waveguerilla** [comment]
Hi,

build:
      context: https://github.com/tuxgasy/docker-dolibarr.git
      dockerfile: ./images/8.0.1-php7.1/Dockerfile

OR

 build:
      context: https://github.com/Dolibarr/dolibarr.git#8.0.1
      dockerfile: build/docker/Dockerfile

**Comment by waveguerilla** [comment]
To reproduce, execute
`docker build -t dolibarr https://github.com/tuxgasy/docker-dolibarr.git#master:images/8.0.1-php7.1`

**Comment by tuxgasy** [comment]
By default, PHP image is now based on Debian Stretch. And the package libpng12-dev was removed on Debian Stretch.
I send a commit to fix it.

**Comment by waveguerilla** [comment]
Ok, it works now, thank you very much.
