### ISSUE TITLE
Should use at least PHP 7.0 not 5.6

### ISSUE THREAD

**Issue by mathieu-rossignol** [tuxgasy/docker-dolibarr#9]
I reproduced this issue https://github.com/Dolibarr/dolibarr/issues/10091 using the docker image 8.0.4 in this current repo.
Basically the problem is that any process that requires sending an email (expense reports request, validation...) does not work and fails because it cannot send an email.
The error is "Parse error: syntax error, unexpected '?' in /var/www/html/includes/swiftmailer/lib/classes/Swift/Mime/SimpleMessage.php on line 496". This is due to PHP 7.0 or above is required by the swift mailer php module.

So you should upgrade the php versions in the docker files. Also for the 9.0.0 dolibarr version.

**Comment by mathieu-rossignol** [comment]
Bad title

**Comment by tuxgasy** [comment]
If you want to use Swift Mailer, there is images with php7.0 or 7.1.

**Comment by mathieu-rossignol** [comment]
It's not that I want to use swift mailer. It is as far as I know the default behaviour of the image. I have tune d nothing and I'm using your image out of the box. If I understand well, that means that you cannot use any feature in the image that requires sending an email in the process. AM I wrong ?

**Comment by tuxgasy** [comment]
All images are just add Dolibarr from original source without modification. So it's the default behaviour of the image because it's default behaviour of Dolibarr.

**Comment by mathieu-rossignol** [comment]
Oh sorry, I thought you wanted me to go and look for images in other repos ! We had a mistunderstanding here. I've just seen your special tags with 7.x php versions in the directories. Thx I'll give it a try and will close the issue. Thank you for your work.

**Comment by mathieu-rossignol** [comment]
Just curious.
- What's the point of using old php if some features are not working with this versions?
- Ok, say it's useful to have old php also, I guess to prevent errors like mine to others, why no using tag names with the latest php version for the dolibarr version tag and special docker images tags for older php versions. I mean 8.0.4 tag should use php 7.1 (latest supported)  and 8.0.4-php5.6 like tags should use older php.

My two cents ;)

**Comment by tuxgasy** [comment]
Because when I started this project, php 7 was not fully supported by Dolibarr.

Maybe, I should not support php 5.6 from Dolibarr 8 or 9... But, I need to review my script to build image for that.

**Comment by mathieu-rossignol** [comment]
Any idea when the 9.0.0 (php7) tag version will be available in docker hub :) ? Thx.

**Comment by tuxgasy** [comment]
The autobuilder must run when I push in this repository. It's was not run with my last push pour Dolibarr 9.

I start it manually. I will be available soon.

**Comment by mathieu-rossignol** [comment]
Thx, will monitor the repo then :)
