### ISSUE TITLE
Kubernetes deployment

### ISSUE THREAD

**Issue by julientrnt** [tuxgasy/docker-dolibarr#90]
Hello, 

I'm trying to deploy a container managed by Kubernetes (hosted by OVH). I have some troubles to use your image as I want.

So first, I can start containers (which one with mariaDB, and the other one based on your image). It works perfectly. However, I absolutly need to mention volumes to keep my data and make them persistent. For this, I'm trying to mount `/var/www/html` (in the dolibarr's container) and `/var/lib/mysql` (in the MariaDB's container) and after that, I can't start anything.

For the MariaDB's issue, I can dodge it by using MySQL, however Dolibarr don't see the Database (returning the message : `Waiting that SQL database is up`). I saw in an other "issues section" that I need to use the command `--default-authentication-plugin=mysql_native_password`. The problem is that I don't know how to setup that in a YAML configuration file designed for Kubernetes.

And finaly, when I specify the volume mount `/var/www/html` on the Dolibarr's container (with MariaDB without volume to start this container), the WEB page returns :
`You don't have permission to access this resource.Server unable to read htaccess file, denying access to be safe`

I hope you could help me.

Best regards.

**Comment by julientrnt** [comment]
Hello @tuxgasy,

Do you have any idea to solve my problem ?

**Comment by damedp** [comment]
Hello
Same problem for me !

**Comment by sebastien-prudhomme** [comment]
Hi @julientrnt, I'm working on a Helm chart for kubernetes. Maybe this PR #93 will fix your first problem.

For the second one, Dolibarr files are in /var/www/documents, not /var/www/html
