### ISSUE TITLE
Cron logs to stdout

### ISSUE THREAD

**Issue by sebastien-prudhomme** [tuxgasy/docker-dolibarr#95]
Before sending a fix, I suggest to push cron logs to stdout/stderr of the PID 1 process instead of writing them to a file.

@tuxgasy what do you think ot it? It would allow to use  the `docker logs` command

**Comment by tuxgasy** [comment]
it's a very good idea.

**Comment by sebastien-prudhomme** [comment]
I see no way to do it without root currently. I'm not sure at all the cron daemon can be launched a a non-root user.

I will revert the cron frequency change to 5 minutes.
